name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
# allow manual trigger

env:
  REFERENCES_URL: https://exmod-team.github.io/SL-References/Dev.zip
  REFERENCES_PATH: ${{ github.workspace }}/References

jobs:
  build:
    runs-on: windows-latest
    permissions:
      packages: read

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Download References
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri ${{ env.REFERENCES_URL }} -OutFile "${{ github.workspace }}/References.zip"
        Expand-Archive -Path "${{ github.workspace }}/References.zip" -DestinationPath ${{ env.REFERENCES_PATH }}

    - name: Rename Assembly-CSharp-Publicized to Assembly-CSharp
      shell: pwsh
      run: |
          Rename-Item -Path "${{ env.REFERENCES_PATH }}\Assembly-CSharp-Publicized.dll" -NewName "Assembly-CSharp.dll"
          
    - name: Build
      env:
        SL_REFERENCES: ${{ env.REFERENCES_PATH }}
      run: dotnet build -o Out

    - name : Upload
      uses: actions/upload-artifact@v4.3.5
      with:
        name: SimpleCustomRoles
        path: Out/*
